#!/usr/bin/env bash

bound_=("c-bound-mcallester" "c-bound-seeger" "c-bound-joint" "bound-risk" "bound-joint")

###################################################################################################

data_=("letter_a_b" "letter_d_o" "letter_o_q" "credit" "haberman" "heart" "glass" "tictactoe" "usvotes" "wdbc")

for data in "${data_[@]}"; do
  for bound in "${bound_[@]}"; do
    sbatch ./run "python optimize_pb_bound.py $data $bound exp_tree.csv $data--$bound --voter=tree --nb-tree=100 --prior=0.5 --not-complemented --not-quasi-uniform --epoch=1000"
    # ----------------------------------------------------------------------------------------------- #
    sbatch ./run "python optimize_pb_bound.py $data $bound exp_stump.csv $data--$bound --voter=stump --nb-per-attribute=20 --not-quasi-uniform --epoch=1000"
  done
done
for data in "${data_[@]}"; do
    sbatch ./run "python optimize_cb_boost.py $data exp_tree.csv $data--cb-boost --voter=tree --nb-tree=100 --prior=0.5"
    sbatch ./run "python optimize_mincq.py $data exp_tree.csv $data--mincq --voter=tree --nb-tree=100 --prior=0.5"
    # ----------------------------------------------------------------------------------------------- #
    sbatch ./run "python optimize_cb_boost.py $data exp_stump.csv $data--cb-boost --voter=stump --nb-per-attribute=20"
    sbatch ./run "python optimize_mincq.py $data exp_stump.csv $data--mincq --voter=stump --nb-per-attribute=20"
done

###################################################################################################

data_=("adult" "mnist_1_7" "mnist_5_6" "mnist_4_9" "fashion_to_pu" "fashion_sa_bo" "fashion_co_sh")

for data in "${data_[@]}"; do
  for bound in "${bound_[@]}"; do
    sbatch ./run "python optimize_pb_bound.py $data $bound exp_tree.csv $data--$bound --voter=tree --nb-tree=100 --prior=0.5 --not-complemented --not-quasi-uniform  --epoch=10 --batch-size=256"
    # ----------------------------------------------------------------------------------------------- #
    sbatch ./run "python optimize_pb_bound.py $data $bound exp_stump.csv $data--$bound --voter=stump --nb-per-attribute=2 --not-quasi-uniform --epoch=10 --batch-size=256"
  done
done
for data in "${data_[@]}"; do
    sbatch ./run "python optimize_cb_boost.py $data exp_tree.csv $data--cb-boost --voter=tree --nb-tree=100 --prior=0.5"
    # sbatch ./run "python optimize_mincq_gd.py $data exp_tree.csv $data--mincq-gd --voter=tree --nb-tree=100 --prior=0.5 --not-complemented --not-quasi-uniform --epoch=10 --batch-size=256"
    # ----------------------------------------------------------------------------------------------- #
    sbatch ./run "python optimize_cb_boost.py $data exp_stump.csv $data--cb-boost --voter=stump --nb-per-attribute=2 --prior=0.5"
    # sbatch ./run "python optimize_mincq_gd.py $data exp_stump.csv $data--mincq-gd --voter=stump --nb-per-attribute=2 --not-quasi-uniform --epoch=10 --batch-size=256"
done

###################################################################################################
