num_trials: 10
num_workers: 4

model:
  M: 4 # number of predictors, if stumps: 2*M per dimension
  prior: 0.1 # param of the Dirichlet prior
  pred: "stumps-uniform" # or "rf"
  bootstrap: 0.5
  tree_depth: None
  m: 0.5 # for informed priors: use first m * N_train points to learn one prior, and last (1-m) * N_train to learn the other prior

training:
  seed: 06042021
  lr: 0.1
  batch_size: 1024
  num_epochs: 100
  risk: "exact" # or MC
  opt_bound: True
  sigmoid_c: 100
  MC_draws: 10

dataset: 'SVMGUIDE'

bound:
  delta: 0.05
  type: "seeger"
  stochastic: False
