num_trials: 10
num_workers: 4

model:
  M: 1 # number of predictors, if stumps: 2*M per dimension
  pred: "stumps-uniform"

training:
  seed: 06042021
  lr: 0.1
  batch_size: 1024
  num_epochs: 100
  risk: 1 # or 2
  opt_bound: True
  sigmoid_c: 100
  MC_draws: 10

dataset: 'MUSH'

bound:
  delta: 0.05
  type: "mcallester"
  stochastic: True