num_trials: 10

model:
  M: 4 # number of predictors, if stumps: 2*M per dimension
  pred: "stumps-uniform"
  boostrap: 0.5
  tree_depth: None
  
training:
  seed: 23032021
  lr: 0.1
  iter: 1e3
  risk: 1 # or 2 or exp
  risk_c: 3
  opt_bound: True

dataset:
  distr: normals # or moons
  N_train: 100 # number of training points per class
  N_test: 1000 # number of test points per class

bound:
  delta: 0.05
  type: "mcallester"
