#!/usr/bin/env python3

import os
import h5py
import numpy as np
import pandas as pd
import random
import warnings
from argparse import ArgumentParser

###############################################################################


if __name__ == "__main__":

    np.random.seed(42)
    random.seed(42)
    warnings.filterwarnings('ignore')

    # We create the parser
    arg_parser = ArgumentParser(
        description="generate the breast-cancer dataset")
    arg_parser.add_argument(
        "old_path", metavar="old_path", type=str,
        help="path of the h5 dataset file")
    arg_parser.add_argument(
        "new_path", metavar="new_path", type=str,
        help="path of the h5 dataset file")
    arg_parser.add_argument(
        "--short", metavar="short", default=200, type=int,
        help="short")


    arg_list = arg_parser.parse_args()
    old_path = arg_list.old_path
    new_path = arg_list.new_path
    short = arg_list.short

    dataset_file = h5py.File(old_path, "r")

    example_train = np.array(dataset_file["x_train"])
    label_train = np.array(dataset_file["y_train"])
    example_test = np.array(dataset_file["x_test"])
    label_test = np.array(dataset_file["y_test"])

    label_list = np.unique(label_train).tolist()

    new_example_train = None
    new_label_train = None
    for y in label_list:
        if(new_example_train is None):
            new_example_train = (example_train[label_train == y])[:short]
            new_label_train = (label_train[label_train == y])[:short]
        else:
            new_label_train = np.concatenate(
                (new_label_train, (label_train[label_train == y])[:short]))
            new_example_train = np.concatenate(
                (new_example_train, (example_train[label_train == y])[:short]))

    if(old_path == new_path):
        dataset_file.close()
    dataset_file = h5py.File(new_path, "w")

    dataset_file["x_train"] = new_example_train
    dataset_file["y_train"] = new_label_train
    dataset_file["x_test"] = example_test
    dataset_file["y_test"] = label_test
