#!/usr/bin/env python3

import os
import h5py
import numpy as np
import pandas as pd
import random
import warnings
from argparse import ArgumentParser

###############################################################################


if __name__ == "__main__":

    np.random.seed(42)
    random.seed(42)
    warnings.filterwarnings('ignore')

    # We create the parser
    arg_parser = ArgumentParser(
        description="generate the breast-cancer dataset")
    arg_parser.add_argument(
        "old_path", metavar="old_path", type=str,
        help="path of the h5 dataset file")
    arg_parser.add_argument(
        "new_path", metavar="new_path", type=str,
        help="path of the h5 dataset file")

    arg_parser.add_argument(
        "class_1", metavar="class_1", type=int,
        help="class_1")
    arg_parser.add_argument(
        "class_2", metavar="class_2", type=int,
        help="class_2")

    arg_list = arg_parser.parse_args()
    old_path = arg_list.old_path
    new_path = arg_list.new_path

    class_1 = arg_list.class_1
    class_2 = arg_list.class_2

    dataset_file = h5py.File(old_path, "r")

    example_train = np.array(dataset_file["x_train"])
    label_train = np.array(dataset_file["y_train"])
    example_test = np.array(dataset_file["x_test"])
    label_test = np.array(dataset_file["y_test"])

    label_train_where = np.where(
        (label_train == class_1) |  (label_train == class_2))[0]
    example_train = example_train[label_train_where, :]
    label_train = label_train[label_train_where]

    label_train[label_train == class_1] = -1
    label_train[label_train == class_2] = +1

    label_test_where = np.where(
        (label_test == class_1) |  (label_test == class_2))[0]
    example_test = example_test[label_test_where, :]
    label_test = label_test[label_test_where]
    label_test[label_test == class_1] = -1
    label_test[label_test == class_2] = +1

    if(old_path == new_path):
        dataset_file.close()
    dataset_file = h5py.File(new_path, "w")

    dataset_file["x_train"] = example_train
    dataset_file["y_train"] = label_train
    dataset_file["x_test"] = example_test
    dataset_file["y_test"] = label_test
