#!/usr/bin/env python3

import os
import h5py
import numpy as np
import pandas as pd
import random
import warnings
from argparse import ArgumentParser

###############################################################################


if __name__ == "__main__":

    np.random.seed(42)
    random.seed(42)
    warnings.filterwarnings('ignore')

    # We create the parser
    arg_parser = ArgumentParser(
        description="generate the breast-cancer dataset")
    arg_parser.add_argument(
        "old_path", metavar="old_path", type=str,
        help="path of the h5 dataset file")
    arg_parser.add_argument(
        "new_path", metavar="new_path", type=str,
        help="path of the h5 dataset file")

    arg_list = arg_parser.parse_args()
    old_path = arg_list.old_path
    new_path = arg_list.new_path

    dataset_file = h5py.File(old_path, "r")

    example_train = np.array(dataset_file["x_train"])
    label_train = np.array(dataset_file["y_train"])
    example_test = np.array(dataset_file["x_test"])
    label_test = np.array(dataset_file["y_test"])

    label_list = np.unique(label_train).tolist()
    for i, y in enumerate(label_list):
        new_label = -1
        if(i >= len(label_list)//2):
            new_label = +1
        label_train[label_train == y] = new_label
        label_test[label_test == y] = new_label

    if(old_path == new_path):
        dataset_file.close()
    dataset_file = h5py.File(new_path, "w")

    dataset_file["x_train"] = example_train
    dataset_file["y_train"] = label_train
    dataset_file["x_test"] = example_test
    dataset_file["y_test"] = label_test
