#!/usr/bin/env python3

import os
import h5py
import numpy as np
import random
from argparse import ArgumentParser


# Initializing the parser
arg_parser = ArgumentParser(description="shuffle a dataset")
arg_parser.add_argument(
    "path", metavar="path", type=str,
    help="path of the h5 dataset file"
)
arg_list = arg_parser.parse_args()

# Getting the argument
dataset_path = arg_list.path
if(not(os.path.exists(dataset_path))):
    arg_parser.error("path must be valid")

# Using "deterministic" split
np.random.seed(42)
random.seed(42)

# Loading the dataset file
dataset_file = h5py.File(dataset_path, "r+")
example_train = dataset_file["example_train"]
example_test = dataset_file["example_test"]
label_train = dataset_file["label_train"]
label_test = dataset_file["label_test"]

# Concatenating the train and test set
example = np.concatenate((example_train, example_test), axis=0)
label = np.concatenate((label_train, label_test), axis=0)

# Shuffling the dataset
permutation = np.arange(example.shape[0])
np.random.shuffle(permutation)
example = example[permutation, :, :, :]
label = label[permutation]

# Modifying the dataset file
del dataset_file["example_test"]
del dataset_file["label_test"]
del dataset_file["example_train"]
del dataset_file["label_train"]
dataset_file["example_test"] = example[example_train.shape[0]:]
dataset_file["label_test"] = label[example_train.shape[0]:]
dataset_file["example_train"] = example[:example_train.shape[0]]
dataset_file["label_train"] = label[:label_train.shape[0]]
